name: Continuous Integration

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Show Go version
        run: go version

      - name: Build
        run: go build -v cmd/*

      - name: Test
        run: go test -v cmd/*

      - name: Lint
        run: go vet cmd/*

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
